language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to install"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed nganguyenduy/udagram-api-feed:v1
  - docker tag udagram-api-user nganguyenduy/udagram-api-user:v1
  - docker tag udagram-frontend nganguyenduy/udagram-frontend:v1
  - docker tag reverseproxy nganguyenduy/reverseproxy:v1

after_success:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u phuongloan --password-stdin
  # Push
  - docker push nganguyenduy/udagram-api-feed:v1
  - docker push nganguyenduy/udagram-api-user:v1
  - docker push nganguyenduy/udagram-frontend:v1
  - docker push nganguyenduy/reverseproxy:v1